### ISSUE TITLE
Debugger is not working

### ISSUE THREAD

**Issue by javaduke** [machaval/mule-esb-plugin#5]
I ran my app in a debugger but it did not stop at the breakpoint. In the event log I see the following:

8:19:58 AM IllegalArgumentException: No enum constant com.mulesoft.mule.debugger.commons.MessageProcessorPathType.process-records
8:20:31 AM Throwable: Assertion failed
8:20:52 AM IllegalArgumentException: No enum constant com.mulesoft.mule.debugger.commons.MessageProcessorPathType.process-records

The breakpoint was not in the batch, it was in a flow at the <logger> line.

Here's the exception:

> No enum constant com.mulesoft.mule.debugger.commons.MessageProcessorPathType.process-records
java.lang.IllegalArgumentException: No enum constant com.mulesoft.mule.debugger.commons.MessageProcessorPathType.process-records
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.mulesoft.mule.debugger.commons.MessageProcessorPathType.valueOf(MessageProcessorPathType.java:12)
	at com.mulesoft.mule.debugger.commons.MessageProcessorPath.fromPath(MessageProcessorPath.java:90)
	at org.mule.util.MuleSupport.getTagAt(MuleSupport.java:216)
	at org.mule.debugger.MuleStackFrame.<init>(MuleStackFrame.java:39)
	at org.mule.debugger.MuleDebugProcess$1.onExceptionThrown(MuleDebugProcess.java:53)
	at org.mule.debugger.session.MuleDebuggerSession$4.run(MuleDebuggerSession.java:183)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:950)
	at org.mule.debugger.session.MuleDebuggerSession.onExceptionThrown(MuleDebuggerSession.java:179)
	at com.mulesoft.mule.debugger.response.MuleMessageArrivedEvent.callCallback(MuleMessageArrivedEvent.java:45)
	at com.mulesoft.mule.debugger.client.DebuggerClient$ServerResponseService.run(DebuggerClient.java:317)
	at java.lang.Thread.run(Thread.java:745)

**Comment by machaval** [comment]
Is this batch? Can you paste the xml where you run this issue with

**Comment by javaduke** [comment]
No, not the batch, although the app does contain a batch. But the breakpoint was in a separate flow that is invoked by http.

**Comment by machaval** [comment]
Fixed now breakpoints should work for most message processors. Batch still is out of scope
